version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatbot-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend-data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - chatbot-network

  frontend:
    build:
      context: ./chatbot-frontend
      dockerfile: Dockerfile
    container_name: chatbot-frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge

volumes:
  backend-data:
